### ISSUE TITLE
Version 1.5.2 denied by Mozilla

### ISSUE THREAD

**Issue by humbertofraga** [xisberto/phonetodesktop-firefox#2]
This version did not pass the review because of the following issues:

1) Your custom CSP allows remote-script injection which is not allowed.

2) Your add-on includes a JavaScript library file that doesn't match any versions known to us. We require all add-ons to use unmodified release versions.

We accept JQuery/JQuery-UI libraries downloaded from 'ajax.googleapis.com', 'jquery.com' or  'jqueryui.com'; and used without any modification (downloaded and not copy pasted). Minified versions are better. (file-name change does not matter)
I'm sorry, but we cannot accept modified, re-configured or customized libraries.
e.g.:
bootstrap/js/bootstrap.js

Please fix them and submit again. Thank you.

**Comment by electron0zero** [comment]
I believe Issue 1 (Your custom CSP allows remote-script injection which is not allowed) is related to content_security_policy key in the manifest. Which I left same as Chrome Extension because I used chrome Extension as a WebExtension base and then ported it to Firefox API.

See more on MDN
https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Reviews
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/content_security_policy

**Comment by electron0zero** [comment]
For issue 2 I am not aware if we load libraries via CDN, If we can then loading libraries using CDN will be best (imo).
